#!/bin/bash

# [[...]] supports &&, ||, < , > operators, but [...] NOT

file=/etc/passwd

if [[ -e $file ]] #true
then
	echo "$file exists"
fi

if [ -e $file ] #true
then
	echo "$file exists"
fi

if [[ 1 < 10 ]] #true
then
	echo "1 < 10"
fi

if [ 1 < 10 ] #error occurs
then
	echo "1 < 10"
fi

