set number
filetype plugin indent on
syntax on
set tabstop=4
set shiftwidth=4
set laststatus=2
set statusline=%<%-10.30f\ %(%l[%L],%c%V%)\ %{&ff}\ %p%%\ %-8.10Y\ 
map <F2> :NERDTreeToggle<CR>

let tlist_php_settings = 'php;c:class;f:function'
let Tlist_GainFocus_On_ToggleOpen = 1 
let Tlist_Close_On_Select = 1 
let Tlist_Sort_Type = "name"

map <F3> :TlistToggle<CR>
map <F5> :set syntax=php<CR>


