jmodule.lo: /home/james/mixedlab/linux/php/jmodule-t/jmodule.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/james/mixedlab/linux/php/jmodule-t $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/james/mixedlab/linux/php/jmodule-t/jmodule.c -o jmodule.lo 
$(phplibdir)/jmodule.la: ./jmodule.la
	$(LIBTOOL) --mode=install cp ./jmodule.la $(phplibdir)

./jmodule.la: $(shared_objects_jmodule) $(JMODULE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_jmodule) $(JMODULE_SHARED_LIBADD)

